# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopoNodos
                                 A QGIS plugin
 Extrai automaticamente os pontos de inflexão do terreno sobre redes de distribuição baseando-se em um MDT.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-05-09
        copyright            : (C) 2025 by Evanderson H. Aguiar
        email                : evanderson.eng@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Evanderson H. Aguiar'
__date__ = '2025-05-09'
__copyright__ = '(C) 2025 by Evanderson H. Aguiar'


def classFactory(iface):
    from .toponodos_provider import TopoNodosProvider
    return TopoNodosProvider()

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopoNodos class from file TopoNodos.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .toponodos import TopoNodosPlugin
    return TopoNodosPlugin()
